### ISSUE TITLE
spatial tests: test_SampledField_samples_mismatchLength_1

### ISSUE THREAD

**Issue by lkeegan** [sbmlteam/libsbml#11]
In `test_SampledField_samples_mismatchLength_1`, this test condition fails for me:

https://github.com/sbmlteam/libsbml/blob/5744b9c3788efb06584cf7fb0a7dc6109d1c12ac/src/sbml/packages/spatial/sbml/test/TestImageData.cpp#L177

This element was initialized from the third element of an array of size 2, so its value is whatever was at that address, which could be anything..

including zero, in which case the test fails.

**Comment by fbergmann** [comment]
indeed, addressing past the end of the array makes for a bad test in any case. the lines should just be removed.

**Comment by fbergmann** [comment]
since the issue is to prevent reads that are out of bounds, we could ensure to use something like: 

```
     sizeof(samples)/sizeof(samples[0]);
```

to determine the actual array length, and if that is smaller than the given length, return an error.

**Comment by lkeegan** [comment]
The user is just passing a pointer and a length:

https://github.com/sbmlteam/libsbml/blob/5744b9c3788efb06584cf7fb0a7dc6109d1c12ac/src/sbml/packages/spatial/sbml/SampledField.h#L765

So I don't think there's any general way to check they have allocated memory correctly - probably you just have to trust that the user is doing it right.

**Comment by fbergmann** [comment]
right .. that trick would only work for memory allocated by [] not for memory allocated by malloc. In that case we'll have to drop those tests. Or at least change it so that none will read past the end of the array. Thanks again
