### ISSUE TITLE
Look at commented out code removeConstraint in Model.cpp

### ISSUE THREAD

**Issue by skeating** [sbmlteam/libsbml#112]
else if (elementName == "constraint")
  {
    // FIXME why is this commented out?
 //   return removeConstraint(id);
  }

**Comment by fbergmann** [comment]
it would be commented out, since constraints had no id's ... and so libsbml had no function to retrieve them by id. You'd need to add that functionality (and it would be safe do so as these days i think we could have an id on them if we so wished).

**Comment by skeating** [comment]
Oh yes - I think I need a holiday :-)
