### ISSUE TITLE
Identifier prefixing

### ISSUE THREAD

**Issue by mihai-sysbio** [sbmlteam/libsbml#151]
I recently became aware of reaction and metabolite identifiers being prefixed with `R_` and `M_` while exporting from Matlab, even though these identifiers do not begin with a number. This is causing problems later for people importing the SBML file and ending up with distinct identifiers than intended.
However, I did notice that in the test suite other metabolites also start with `M_` even if they would not have a number as the first character, so I am unsure if this is a feature or a bug.

Could you please shed some light on this?

**Comment by fbergmann** [comment]
This syntax is (or was) used by the COBRA matlab toolbox, and for many years models from the FBC community have been published with them. The models in the test suite contains such models, as libSBML can convert from the official FBC extension to this old COBRA format as part of the FBC package. 

It is not encouraged to use semantic prefixing of model ids. But every tool is free to choose to write SBML how they see fit.

**Comment by mihai-sysbio** [comment]
Many thanks for the explanation @fbergmann - it enabled us to identify the lines of code in the RAVEN toolbox at the root of the issue, it had nothing to do with libSBML.

**Comment by skeating** [comment]
Thanks for letting us know

**Comment by haowang-bioinfo** [comment]
A follow-up question about identifiers, if libSBML can report errors or warnings when illegal model ids (e.g. begin with numbers) are detected?

**Comment by luciansmith** [comment]
It does!  If you validate the model, you will get the error 10310, "The syntax of 'id' attribute values must conform to the syntax of the SBML type 'SId'."

**Comment by luciansmith** [comment]
(Also, a call to 'setId' will fail and return an error code if you call it with an illegal argument.)

**Comment by haowang-bioinfo** [comment]
Thanks @luciansmith !

If one plan to validate a model, how to do this under Python or Matlab environment?

**Comment by fbergmann** [comment]
You would simply call `checkConsistency` on the document and look at entries in the error log. We do have an example online: 

<https://github.com/sbmlteam/libsbml/blob/development/examples/python/validateSBML.py>

i hope this helps.

**Comment by haowang-bioinfo** [comment]
yes, it does @fbergmann
