### ISSUE TITLE
Nightly build failure due to R binding issue 

### ISSUE THREAD

**Issue by fbergmann** [sbmlteam/libsbml#161]
The last nightly build failed with: 

<https://github.com/sbmlteam/libsbml/actions/runs/1149525633>

looking into it it is caused by the R headers not being found, i assume this is because the build environment will have been upgraded to a higher version of R. So the action will need to be updated.

**Comment by alessandrofelder** [comment]
I'll have a look at some point this week - thanks!

**Comment by alessandrofelder** [comment]
Indeed, it looks like the Windows-2019 specs were recently updated [from R 1.1.0 to R 1.1.1](https://github.com/actions/virtual-environments/commit/c706ecc11c769c4d115911da8bdde2e8fcd8b378) and we have 1.1.0 hard-coded in our GHA yml files.
