### ISSUE TITLE
Install in Octave

### ISSUE THREAD

**Issue by davidnarganes** [sbmlteam/libsbml#165]
Hi,

I am using Octave installed through brew on a MacOS BigSur 11.6: https://wiki.octave.org/Octave_for_macOS
I am not very familiar with this language but,

I'm trying to install your library and add the path but it doesn't work:
```
% addpath("/Users/dnarganes/repos/insiliko/src/libSBML-5.18.0-matlab-binaries");
% addpath("/Users/dnarganes/repos/insiliko/src/libsbml-5.17-1.0-matlab-binaries");
% addpath("/Users/dnarganes/repos/insiliko/src/libSBML-5.18-2.0-matlab-oldmacosx-binaries");
% addpath("/Users/dnarganes/repos/insiliko/src/libSBML-5.18.0-matlab-binaries");
addpath("/Users/dnarganes/repos/insiliko/src/libSBML-5.18-3.0-matlab-oldmacosx-binaries");

filename = "BIOMD0000000404.xml"
validateFlag = 0
verboseFlag = 1
[model, errors, version] = TranslateSBML(filename, validateFlag, verboseFlag);
```

Error is:
```
error: invalid call to script /Users/dnarganes/repos/insiliko/src/libSBML-5.18-3.0-matlab-oldmacosx-binaries/TranslateSBML.m
error: called from
    TranslateSBML
```

- Why the `TranslateSBML()` is not in `libSBML-5.18.0-matlab-binaries`?
- Why `TranslateSBML()` looks like an empty function on `libSBML-5.18-3.0-matlab-oldmacosx-binaries`?
- Why I get that error https://wiki.octave.org/FAQ#Error_message_about_invalid_call_to_script_or_invalid_use_of_script_in_index_expression if it does not override built-in functions in Octave?

**Comment by fbergmann** [comment]
the matlab binaries have been built for matlab only. What is happening here, is that octave cannot call the pre-compiled matlab bindings, as they won't with octave. Those would have to be compiled from scratch (though we are not sure how much recent octave versions have deviated, from the code that we had working at one point).

**Comment by davidnarganes** [comment]
No worries, I will use Python instead. Thanks!
https://pypi.org/project/python-libsbml/ seems to work so far

**Comment by skeating** [comment]
octave build working
