### ISSUE TITLE
`python-libsbml==5.19.2` release misses parts of distrib

### ISSUE THREAD

**Issue by matthiaskoenig** [sbmlteam/libsbml#199]
Hi all,
I just wanted to switch from the python package
`python-libsbml-experimental==5.19.0`
to
`python-libsbml==5.19.2`

But objects from the accepted distrib package are missing in the release. I.e. things such as
```
from libsbml import Uncertainty
```
are not working any more. 

Did the naming of the classes change? Or are parts missing from the release?
Could you make a new stable release which includes all of the distrib package?

Best Matthias

**Comment by fbergmann** [comment]
yes, i create a new build ... since it will use the same version of libsbml, i'll issue a new build number for the wheel.

**Comment by matthiaskoenig** [comment]
Thanks, perfect.

**Comment by fbergmann** [comment]
Unfortunately, as it turns out while build numbers work great for windows and macos, they dont work with auditwheel, so we will have to change the version number of libsbml.

**Comment by matthiaskoenig** [comment]
What is the timeline for the new release?

**Comment by fbergmann** [comment]
the wheels, were all done but unfortunately auditwheel removed the extra build number, so unfortunately the windows wheels were rejected.

**Comment by fbergmann** [comment]
had to push the wheels as  5.19.3 (they are up now). will tag libsbml and do conda packages tomorrow  i hope

**Comment by matthiaskoenig** [comment]
Thanks. Works for me. Issue solved.

**Comment by fbergmann** [comment]
libsbml-experimental 5.19.3 now also on pypi

**Comment by fbergmann** [comment]
conda-forge is now also updated, so i'm closing this
