### ISSUE TITLE
where are the example files from the specification?

### ISSUE THREAD

**Issue by anandijain** [sbmlteam/libsbml#202]
There are a number of example SBML files in the specification https://sbml.org/documents/specifications/level-3/ (that I believe are not test cases in sbml-test-suite), but unfortunately copy-pasting from the PDF garbles the content. I am wondering if these examples can be found somewhere. 

I realize this isn't the correct repo for this issue, but you all are quite responsive here :). Thanks

**Comment by luciansmith** [comment]
They can!  We're still in the process of moving stuff to github, but in the meantime, everything can be found at sourceforge:

https://sourceforge.net/p/sbml/code/HEAD/tree/trunk/specifications/sbml-level-3/version-2/core/spec/examples/

**Comment by skeating** [comment]
There is new git repo https://github.com/sbmlteam/sbml-specifications which does contain all these
