### ISSUE TITLE
Can't import python libsbml on M1 mac after pip install

### ISSUE THREAD

**Issue by teddygroves** [sbmlteam/libsbml#206]
I can't import python-libsbml on my computer after pip installing it. 

I think the error is saying that the provided `.so` file has x86 architecture, even though the wheel is supposed to be arm specific.

Are there any instructions available for building python-libsbml locally?

## Steps to reproduce:

```
(.venv_maud) ➜  maud_data git:(master) ✗ pip install --no-cache-dir python-libsbml
Collecting python-libsbml
  Downloading python_libsbml-5.19.3-cp310-cp310-macosx_11_0_arm64.whl (5.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 13.8 MB/s eta 0:00:00
Installing collected packages: python-libsbml
Successfully installed python-libsbml-5.19.3
(.venv_maud) ➜  maud_data git:(master) ✗ python -c "import libsbml"               
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/tedgro/.venvs/.venv_maud/lib/python3.10/site-packages/libsbml/__init__.py", line 28, in <module>
    from . import _libsbml
ImportError: dlopen(/Users/tedgro/.venvs/.venv_maud/lib/python3.10/site-packages/libsbml/_libsbml.cpython-310-darwin.so, 0x0002): tried: '/Users/tedgro/.venvs/.venv_maud/lib/python3.10/site-packages/libsbml/_libsbml.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/_libsbml.cpython-310-darwin.so' (no such file), '/usr/lib/_libsbml.cpython-310-darwin.so' (no such file)
```

## System info
python version: 3.10.1
pip version: 22.0.4
operating system: macos 12.1
chip: Apple M1 Max

**Comment by fbergmann** [comment]
thanks for letting us know, we switched to using cibuildwheels for building the platform wheels, but clearly something went wrong along the way. I'm not quite sure where it went wrong, so will have to debug this: 

<https://github.com/sbmlteam/python-libsbml/runs/5288972919?check_suite_focus=true>

**Comment by fbergmann** [comment]
We've created a new 5.19.4 release on pypi to adress this issue.
