### ISSUE TITLE
getPackageRequired ignores package name

### ISSUE THREAD

**Issue by eltix** [sbmlteam/libsbml#215]
## Issue description

The full model:
[SbmlWithComp.log](https://github.com/sbmlteam/libsbml/files/8519941/SbmlWithComp.log) (change the extension from `.log` to `.xml` to reproduce, github does not accept the latter for attachments)

The interesting bit:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<sbml xmlns:comp="http://www.sbml.org/sbml/level3/version1/comp/version1" xmlns="http://www.sbml.org/sbml/level3/version2/core" level="3" version="2" comp:required="true">
  <model id="case01355" name="case01355">
```

When loading the above SBML model, the `getPackageRequired` function invariably returns `0` when supplied `"comp"` as package parameter.
However [the doc for this function](https://sbml.org/software/libsbml/5.18.0/docs/formatted/c-api/class_s_b_m_l_document__t.html#abf9dde83144945cd14bead4717e8afdd) suggests that one can pass either the package name or the package URI:
```
int SBMLDocument_getPackageRequired	(	SBMLDocument_t * 	d,
const char * 	package 
)		
Returns the required attribute of the given package extension.

Parameters
d	the SBMLDocument_t structure to check.
package	the name or URI of the package extension.
Returns
1 (true) if the package is flagged as being required in this SBML document, 0 (false) otherwise.
```

Passing the full URI `"http://www.sbml.org/sbml/level3/version1/comp/version1"` works as expected, _i.e._ returns `0` when `comp:required="false"` and `1` when `comp:required="true"`.

**Comment by fbergmann** [comment]
Trying it with [python](https://colab.research.google.com/drive/1hZU5YSvVMcpeGlLWMkh_o4DEs4nElVRp?usp=sharing), i can confirm, that it works with either name or Uri. 

So we need more information as to how libsbml is configured on your machine. Which version, operating system, and the configuration options of libSBML. 

Edit: it is likely that your version of libSBML was compiled without support for the comp package, you will need the cmake option `-DENABLE_COMP=ON` to ensure it is compiled with comp support.

**Comment by eltix** [comment]
Thank you @fbergmann 
Indeed, it doesn't look like we have added the cmake options you mention. We use libsbml's C library, packaged with the following nix configuration:
```nix
{ stdenv, fetchurl, cmake, libxml2 }:
stdenv.mkDerivation rec {
  pname = "libsbml";
  version = "5.17.0";

  src = fetchurl {
    url =
      "mirror://sourceforge/sbml/libsbml/${version}/stable/libSBML-5.17.0-core-src.tar.gz";
    sha256 = "153l67jb1q888y91kb439bwy6d3vsz4aqgpbcqhskmg842bx4axb";
  };

  buildInputs = [ cmake libxml2.dev ];

  preConfigure = ''
    # To force the use of cmake instead of autotools
    rm ./configure

    # For some reason cmake doesn't have the right include path for libxml2, so
    # we explicitely gave him here
    export CMAKE_INCLUDE_PATH=${libxml2.dev}/include/libxml2:$CMAKE_INCLUDE_PATH
  '';
}
```
Will try with the cmake option and report below.

**Comment by fbergmann** [comment]
Actually, looking at the url, you seem to be downloading the file for libSBML core only. This will not include any of the packages, i suggest to use [libSBML-5.17.0-core-plus-packages-src.tar.gz](https://sourceforge.net/projects/sbml/files/libsbml/5.17.0/stable/libSBML-5.17.0-core-plus-packages-src.tar.gz/download) that includes all stable packages.

**Comment by eltix** [comment]
Thank you Frank, with the following config it works as expected:
```nix
  src = fetchurl {
    url =
      "mirror://sourceforge/sbml/libsbml/${version}/stable/libSBML-5.17.0-core-plus-packages-src.tar.gz";
    sha256 = "0fpdw3w129s5j74kmcjc8njhfz96g5mm073r9d3f8xr78zhid4hq";
  };

  cmakeFlags = [
    "-DENABLE_COMP=ON"
  ];
 ```
 I think I can safely say my issue is fixed. However, may I recommend some documentation improvements? 
 
 I think that [installing libSBML with package support](https://sbml.org/software/libsbml/5.18.0/docs/formatted/c-api/libsbml-installation.html) is properly documented. However the behavior of `getPackageRequired` is, in my opinion, rather confusing because it depends on some configuration options (the aforementioned CMAKE flags). 
Perhaps we could explain in the doc that passing the package nickname only works if libsbml was compiled with package support? Otherwise, the URI must be passed.
Going even further (and this would make the behavior of the function independent of the config), would it be possible to support passing package nicknames regardless of the config? 
Feel free to disregard these comments.

Just to avoid any XY problem, this is our end goal: we want to check whether an SBML document requires a package that we do not yet support. To that end, we call `getPackageRequired` with every unsupported package name, then log and throw an error if any is required.

**Comment by fbergmann** [comment]
I think the way to go about this, is to look at the errors logged during reading. In your original case, the error log would already contain an error: 

```
line 2: (99107 [Error]) Every SBML Level 3 package is identified uniquely by an XML namespace URI and defines the attribute named 'required'. A value of required=true indicates that interpreting the package is necessary for complete mathematical interpretation of the model. (L3V1 Section 4.1.2) This instance of libSBML version 5 cannot find the code necessary to interpret the package information.
 Package 'comp' is a required package and the model cannot be properly interpreted.
```

indicating, that there was a required package used, but not supported. (If required were set to false, it would be only a warning). 

So libSBML already performs the validation for you. And you can easily check for it. 

The reason, we don't automatically accept the 'name' of the package, because all we know at this point, is that an xml namespace was defined with a prefix, and for that prefix we have a required attribute. We don't know whether that prefix is a package name, as at that point we don't have the package names of the extensions available. 

But i agree, the documentation can and should be amended to avoid this confusion in the future.
