### ISSUE TITLE
local listOfParameters in L2V4 should be converted to listOfLocalParameters in L3V2

### ISSUE THREAD

**Issue by eltix** [sbmlteam/libsbml#224]
## Issue description

In SBML [L2V4](http://co.mbine.org/specifications/sbml.level-2.version-4.release-1.pdf#page=70) it is possible to define `Parameter`s that are local to a `Reaction` through a `listOfParameters` field under `kineticLaw`.
In SBML [L3V2](https://co.mbine.org/specifications/sbml.level-3.version-2.core.release-2.pdf#page=74), `listOfParameters` has been renamed to `listOfLocalParameters` to avoid any confusion with the global (model-wide) `listOfParameters`. 
However libSBML's [setLevelAndVersion](https://synonym.caltech.edu/software/libsbml/5.18.0/docs/formatted/python-api/classlibsbml_1_1_s_b_m_l_document.html#a8860a47a8c47b116f48f54274f39080d) method does not seem to be doing the renaming when converting from `L2V4` to `L3V2` and therefore produces invalid L3V2 documents.

### To reproduce

Here is an example of L2V4 SBML model (which comes from [here](https://www.ebi.ac.uk/biomodels/search?offset=100&numResults=10&sort=id-asc&query=*%3A*+AND+curationstatus%3A%22Manually+curated%22+AND+modelformat%3A%22SBML%22+AND+modellingapproach%3A%22Ordinary+differential+equation+model%22&domain=biomodels)):
[BIOMD0000000505.log](https://github.com/sbmlteam/libsbml/files/8603644/BIOMD0000000505.log)
(change the extension from `.log` to `.xml`)

After running it through `setLevelAndVersion(3, 2)` this is the output:
[ConvertedToL3V2.log](https://github.com/sbmlteam/libsbml/files/8603650/ConvertedToL3V2.log)
which contains `listOfParameters` blocks inside `kineticLaw`s.

Note that `checkL3v2Compatibility()` does not return any error, nor do `checkInternalConsistency()` and `checkConsistency()` (there are some warnings regarding units but they are not relevant for the present issue).

### Configuration

We use nix to package `libSBML` and below is its configuration file:
```
{ stdenv, fetchurl, cmake, libxml2 }:
stdenv.mkDerivation rec {
  pname = "libsbml";
  version = "5.17.0";

  src = fetchurl {
    url =
      "mirror://sourceforge/sbml/libsbml/${version}/stable/libSBML-5.17.0-core-src.tar.gz";
    sha256 = "153l67jb1q888y91kb439bwy6d3vsz4aqgpbcqhskmg842bx4axb";
  };

  buildInputs = [ cmake libxml2.dev ];

  preConfigure = ''
    # To force the use of cmake instead of autotools
    rm ./configure

    # For some reason cmake doesn't have the right include path for libxml2, so
    # we explicitely gave him here
    export CMAKE_INCLUDE_PATH=${libxml2.dev}/include/libxml2:$CMAKE_INCLUDE_PATH
  '';
}
```

**Comment by fbergmann** [comment]
I think what happens here, is that the libSBML 5.17 was released before Level 3 Version 2, so there is no special code there for this. When i try this at my local 5.19 version, i dont see this behavior. 

Would there be any chance you could get the source code from this repository, rather than the old sourceforge version?

If that is not the issue, i would have to see the precise code that you were using, i was just doing

```
import libsbml
doc = libsbml.readSBMLFromFile('BIOMD0000000505.log')
doc.setLevelAndVersion(3,2)
libsbml.writeSBMLToFile(doc, 'biomd505-3-2.xml')
```

and the resulting file had localParameters.

**Comment by eltix** [comment]
Thank you again @fbergmann for looking at this. I've bumped to libSBML 5.19 (did not realize our version was so old), alas it breaks many things on our end. Will report when dust settles.

**Comment by eltix** [comment]
@fbergmann Indeed it works fine with 5.19, thanks a lot.
Should we maybe add a comment in `setLevelAndVersion()`'s doc saying that the conversion to L3V2 may be incomplete in versions <5.19? It's not obvious because according to the code it is able to conver to L3V2, there's even a `checkL3v2Compatibility()` function

**Comment by fbergmann** [comment]
I'm not sure what a comment would help at this point. Whatever the bug was in 5.17 it has since been resolved. Adding a comment to each method that at one point had a bug seems counter productive. For each full release we try to note things down in the [NEWS.txt](https://github.com/sbmlteam/libsbml/blob/development/NEWS.txt) file.

**Comment by eltix** [comment]
Fair enough, I'll close the issue then
