### ISSUE TITLE
Missing whitespace in chemicalFormula warning

### ISSUE THREAD

**Issue by matthiaskoenig** [sbmlteam/libsbml#238]
Please change:         
```
message += "The chemicalFormula '";
```
to 
```
message += " The chemicalFormula '";
```
in https://github.com/sbmlteam/libsbml/blob/23dc2fba2dcbce422c2d1ff08dc80ff670e432d1/src/sbml/packages/fbc/extension/FbcSpeciesPlugin.cpp#L129

See for instance
https://github.com/opencobra/cobrapy/issues/1242#issuecomment-1169476085

Unfortunately, I cannot create a simple pull request because the repository is having submodules and the respective code is not part of the repository if I fork the repository. Could you provide me access to create pull requests for simple typo fixes?

Best Matthias

**Comment by fbergmann** [comment]
this has now been merged into development and will be part of the next release. Thanks
