### ISSUE TITLE
`fbc-v3`: Naming of UserDefinedConstraint differs from specification draft

### ISSUE THREAD

**Issue by matthiaskoenig** [sbmlteam/libsbml#242]
The naming of the `UserDefinedConstraint` is different in specification and should likely be `UserConstraint`.
(this affects also the `ListOf*` and the `*Component`. Not sure if this is an issue with the specification or the library, but they are out of sync.

https://sourceforge.net/p/sbml/code/26312/tree/trunk/specifications/sbml-level-3/version-1/fbc/spec/main.pdf?format=raw

**Comment by fbergmann** [comment]
I think that is an issue of brett having moved to github at that point to edit the spec. In discussions it was decided to call it `UserDefinedConstraint`. I believe the latest version of the spec is: 

<https://github.com/bgoli/sbml-fbc-spec/blob/main/sf_svn/spec/main.pdf>

@bgoli  to verify.

**Comment by bgoli** [comment]
Confirmed on both accounts, it is UserDefinedConstraint and that is my latest version of the spec. I've been meaning to ask, are the package specs now also now on GitHub?

**Comment by matthiaskoenig** [comment]
Perfect. I remember the discussions. I just could not find the latest spec document in sourceforge.

**Comment by matthiaskoenig** [comment]
The core specifications are at https://github.com/sbmlteam/sbml-specifications/
I don't know if the package specifications have already be migrated to github. @luciansmith probably knows more about that

**Comment by luciansmith** [comment]
Indeed, all the specs have moved to github.

Perhaps the best thing to do would be to make an update to the sourceforge that removes everything and replaces it with a link to github.

**Comment by bgoli** [comment]
Thanks @luciansmith I will look into the github specs. Just as a general FYI I plan to finalize the integration of the "proposal" into the main spec text over the next few weeks, with the idea that it can be accepted (baring last minute textual issues) at combine. My general opinion is that what we have now is in terms of design and implementation is good to go. 

Great that you are implementing support @matthiaskoenig. From my side, there should be no implementation affecting changes introduced into the current document.
