### ISSUE TITLE
fbc-v3: new FBC constants for `fbcVariableType` are named inconsistently

### ISSUE THREAD

**Issue by matthiaskoenig** [sbmlteam/libsbml#251]
I just noticed that the constants for FBC are not named consistently.

The existing constants are for `objective.type`
```
libsbml.OBJECTIVE_TYPE_MINIMIZE
libsbml.OBJECTIVE_TYPE_MAXIMIZE
```
Whereas the new constant for `fbcVariableType` are prefixed with FBC and the `_` separation is different
```
libsbml.FBC_FBCVARIABLETYPE_LINEAR
libsbml.FBC_FBCVARIABLETYPE_QUADRATIC
libsbml.FBC_FBCVARIABLETYPE_INVALID
```
These should probably be
```
libsbml.FBC_VARIABLE_TYPE_LINEAR
libsbml.FBC_VARIABLE_TYPE_QUADRATIC
libsbml.FBC_VARIABLE_TYPE_INVALID
```

**Comment by fbergmann** [comment]
I'm fine with that change. Given that FBC v3 has not been accepted yet, I would prefer to leave that renaming until we have collected all changes you still need.

**Comment by matthiaskoenig** [comment]
Perfect.
