### ISSUE TITLE
Matlab OutputSBML fails with nondescript error

### ISSUE THREAD

**Issue by tpfau** [sbmlteam/libsbml#268]
Hi,

I'm currently encountering a situation, where the OutputSBML function in matlab fails with a nondescript error "Failed to write file". 
I'm wondering, whether it would be possible to make this output a bit more verbose. 
From my understanding, this could probably be done by retrieving the actual error log and appending it to the string of the error message.
Something along the lines
```
SBMLErrorLog *log = sbmlDocument.getErrorLog();
reportError("OutputSBML:writeFile", log->toString(), gv);
```
instead of the original:
```
reportError("OutputSBML:writeFile", "Failed to write file", gv);
```

This would allow to better understand what might be going wrong, as I currently have no idea, where things might be going wrong since the struct itself seems to be fine.

**Comment by skeating** [comment]
added
