### ISSUE TITLE
Missing inclusion of a header in StructureFields.cpp, version 5.19.7

### ISSUE THREAD

**Issue by pgrt** [sbmlteam/libsbml#282]
Hello,

In StructureFields.cpp in the matlab bindings, FbsAccosiation cannot be found as its header is not included. The attached patch allows one to compile successfully.

[missing_header.txt](https://github.com/sbmlteam/libsbml/files/10096268/missing_header.txt)

Best,
Pierre

**Comment by skeating** [comment]
added
