### ISSUE TITLE
Idea: Add more biological qualifiers

### ISSUE THREAD

**Issue by GwennyGit** [sbmlteam/libsbml#283]
I am currently using libSBML to improve annotations with CVTerms in my model. For the unit definitions I wanted to add the biological qualifier 'isDerivedFrom', however, currently this qualifier does not exist in libSBML. As can be seen here: https://github.com/sbmlteam/libsbml/blob/efc1992fe45386aef25d84dfe376541de8344344/src/sbml/annotation/CVTerm.h#L400 It would be nice if you could add more biological qualifiers like for example in the cobratoolbox (see here: https://github.com/opencobra/cobratoolbox/blob/37c922c422a19d731da66e81059ec0989db39418/src/base/io/utilities/SBML/getBioQualifiers.m). I would appreciate that as I could use libSBML further for the task and would not have to switch to another program.

Thank you for considering my request.

**Comment by luciansmith** [comment]
isDerivedFrom is in bqmodel, but not bqbiol, at least for now.  See:

https://web.archive.org/web/20211204231945/http://co.mbine.org/specifications/qualifiers

I guess cobratoolbox needs to be updated?

In the meantime, you should be able to use libsbml, I hope?  Just use isDerivedFrom from the model qualifiers list.

Filed issue with cobrapy at https://github.com/opencobra/cobratoolbox/issues/2080

**Comment by GwennyGit** [comment]
Thank you for the fast reply. 

As I took a closer look at the descriptions in the provided link for the qualifier specifications, I realised that I need model qualifiers and not biological qualifiers for my task anyway.

Please excuse any inconveniences caused by this request.
