### ISSUE TITLE
Time zones with offsets below -11:59 and above 11:59 are not accepted by the Date class

### ISSUE THREAD

**Issue by avandecreme** [sbmlteam/libsbml#289]
The hour offset is checked to be at most `11` here: https://github.com/sbmlteam/libsbml/blob/226c8674bdfb5b28ac58b0b2046a44f2f8781bfd/src/sbml/annotation/Date.cpp#L648

This prevent representing some time zones, for example [LINT](https://www.timeanddate.com/time/zones/lint) is UTC+14 and [AoE](https://www.timeanddate.com/time/zones/aoe) is UTC-12.

Would you be interested by a patch fixing this?

**Comment by fbergmann** [comment]
thank you for letting us know, a patch would certainly be helpful. Should you not have time to do that, we'll be able to construct test cases now that you have let us know. Thank yoiu
