### ISSUE TITLE
Python 3.11 support?

### ISSUE THREAD

**Issue by tillea** [sbmlteam/libsbml#293]
Hi,
Debian is switching to Python 3.11.  Do you support this Python version officially or should I expect issues since this is not tested yet?
Kind regards, Andreas.

**Comment by fbergmann** [comment]
We have [3.11](https://pypi.org/project/python-libsbml/) binary wheels up at pypi. So we have been compiling libsbml just fine for 3.11. You will need the latest github release 5.19.7. Please let us know if you encounter any issues.

**Comment by tillea** [comment]
Am Mon, Jan 16, 2023 at 01:30:06PM -0800 schrieb Frank Bergmann:
> We have [3.11](https://pypi.org/project/python-libsbml/) binary wheels up at pypi. So we have been compiling libsbml just fine for 3.11. You will need the latest github release 5.19.7. Please let us know if you encounter any issues. 
Thanks for confirming this.
