### ISSUE TITLE
'Latest' version isn't latest.

### ISSUE THREAD

**Issue by luciansmith** [sbmlteam/libsbml#297]
On the sidebar from the main site, it claims that the 'latest' version of libsbml is 5.19.0.  However, if you click on 'releases', you see 5.19.7

Does 5.19.7 not have all the bits and bobs that the 'full' release does?

**Comment by fbergmann** [comment]
it does have much more. but since we have not been able to do the full binary release stuff, we've held back with making full releases.

**Comment by fbergmann** [comment]
we've made them available as pre-releases because of that: 

<https://github.com/sbmlteam/libsbml/releases/tag/v5.19.7>

**Comment by luciansmith** [comment]
Is the build system not working for doing a full binary release?  It's been over two years; it seems like fixing that should be a high-ish priority.

OTOH, most people seem to just use python these days, and that's still working; maybe we can just put those wheel files in the release and call it a day?  Just use the python binaries, source code tarball, and documentation?  If people ask for other binaries maybe we can do one-offs for those systems?

**Comment by fbergmann** [comment]
5.19.7 for python is available on pypi and condo, so those binaries are there. what is missing is Matlab for all platforms, and we are working on that. The other thing we are working on is the documentation builds. It just takes some time.

**Comment by fbergmann** [comment]
this is now fixed with todays release! Latest is indeed latest for today.
