### ISSUE TITLE
bug in `SBMLTransforms::replaceFD`?

### ISSUE THREAD

**Issue by lkeegan** [sbmlteam/libsbml#299]
I was using `SBMLTransforms::replaceFD` to expand/inline functions in math expressions but ran into incorrect results in some cases:

https://github.com/spatial-model-editor/spatial-model-editor/issues/856#issuecomment-1451919941

I think substituting each argument sequentially like this is only valid if there is no overlap between the variables in the function body and the variables that are passed to the function?

**Comment by fbergmann** [comment]
This has now been fixed and merged into development. We plan to have a new release including the fix within the next couple of weeks.

**Comment by lkeegan** [comment]
@fbergmann thanks! Unfortunately while this fixes the failing test case I don't think it is correct in general, e.g. changing the expression from `p * S1` to `p - S1` gives incorrect results. I think to do the substitution correctly it needs to be done for all variables at the same time - I've made a PR with an attempt at doing this here: #303
