### ISSUE TITLE
libsbml writing out empty <listOfReactants/>

### ISSUE THREAD

**Issue by luciansmith** [sbmlteam/libsbml#319]
This is a change of behavior from not long ago:  if I flatten the attached model, I now get <listOfReactants/> and didn't use to.  Is this behavior intentional?

[deleteReactant.xml.txt](https://github.com/sbmlteam/libsbml/files/11391780/deleteReactant.xml.txt)

**Comment by luciansmith** [comment]
Correction!  This is a difference in behavior of an L3v1 model vs. an L3v2 model, because of Reaction::writeElements, which checks

```
    if (mReactants.hasOptionalElements() == true ||
        mReactants.hasOptionalAttributes() == true ||
        mReactants.isExplicitlyListed())
    {
      mReactants.write(stream);
    }
```

Is there an obvious place to turn off isExplicitlyLIsted in the flattening routines, assuming we need to do that there?

**Comment by fbergmann** [comment]
There is 

```c++

ListOf::setExplicitlyListed(bool value)

```

so you should be able to set it on all lists you want during the flattening procedure.

**Comment by skeating** [comment]
Lucian sorted this
