### ISSUE TITLE
Linking against libsbml 5.20 via CMake leads to an error.

### ISSUE THREAD

**Issue by adelhpour** [sbmlteam/libsbml#332]
This is the error I get when I try to configure my project in which I am building a library linked to libsbml.

CMake Error at C:/Users/adel/Documents/Projects/Built/libsbml/install/share/cmake/Modules/FindBZ2.cmake:55 (check_library_exists):
  Unknown CMake command "check_library_exists".

CMake Error at C:/Users/adel/Documents/Projects/Built/libsbml/install/share/cmake/Modules/FindLIBXML.cmake:124 (CHECK_C_SOURCE_COMPILES):
  Unknown CMake command "CHECK_C_SOURCE_COMPILES".

I think there are some missing modules in find-dependency-.cmake scripts. I have modified those scripts and created the pull request #331

**Comment by fbergmann** [comment]
Thank you for the PR, I've just approved and merged it.
