### ISSUE TITLE
Segmentation fault with some operations after failed strict conversion

### ISSUE THREAD

**Issue by avandecreme** [sbmlteam/libsbml#333]
The following program seg fault when run with the [following uncompressed file](https://github.com/sbmlteam/libsbml/files/11601071/conversion_seg_fault.zip).

```c
printParentDocIsNull(SBMLDocument_t * d)
{
  Model_t *m = SBMLDocument_getModel(d);
  SBMLDocument_t *d2 = SBase_getSBMLDocument((SBase_t *)m);
  printf("Parent doc is null: %i\n", d2 == NULL);
}


int
main (int argc, char *argv[])
{
  int success;
  SBMLDocument_t *d = readSBML(argv[1]);
  printParentDocIsNull(d);
  success = SBMLDocument_setLevelAndVersionStrict(d, 3, 2);
  printf("Strict Success: %d\n", success);
  printParentDocIsNull(d);
  success = SBMLDocument_setLevelAndVersionNonStrict(d, 3, 2);
  printf("Non Strict Success: %d\n", success);
  printParentDocIsNull(d);
  SBMLDocument_checkConsistency(d);

  SBMLDocument_free(d);
  return 0;
}
```

Result in:
```
Parent doc is null: 0
Strict Success: 0
Parent doc is null: 1
Non Strict Success: 1
Parent doc is null: 1
Segmentation fault (core dumped)
```

I tracked down the issue to the fact when failing to do a strict conversion, we restore the model of the document to a stored copy here:
https://github.com/sbmlteam/libsbml/blob/49ce5b40ead6862c1a610a569d0606f03a4fb4fa/src/sbml/conversion/SBMLLevelVersionConverter.cpp#L424

However, copying a model does not copy the `mSBML` field on `SBase`:
https://github.com/sbmlteam/libsbml/blob/49ce5b40ead6862c1a610a569d0606f03a4fb4fa/src/sbml/SBase.cpp#L421
This is put in evidence by the `Parent doc is null` outputs above.

This then cause the crash when running the consistency check on unique ids because the following line trust that `m.getSBMLDocument()` will return a non null value:
https://github.com/sbmlteam/libsbml/blob/49ce5b40ead6862c1a610a569d0606f03a4fb4fa/src/sbml/validator/constraints/UniqueIdsInModel.cpp#L166

I am able to fix that specific issue by adding the following line when cloning the model in the `SBMLLevelVersionConverter`:
```cpp
          currentModel->connectToParent(mDocument);
```
However, I am not sure this is the best approach because all other `SBase` (reactions, compartments...) of the model will still be missing there back link to the document.

Any idea how to best fix this?

**Comment by skeating** [comment]
Thanks for the report. 
Yes I need to think about this - there are other places where functions like this will recurse down the whole tree but I need to look at this before I'm convinced this is the right approach here

**Comment by skeating** [comment]
I can see exactly where this is happening but it will only happen when a model has been converted but then fails validation. Do you happen to have a small example which will save me trying to find one? Thanks

**Comment by skeating** [comment]
Sorry I've just spotted it
