### ISSUE TITLE
issues about "--enable-fbc --enable-groups" in Mac M1 

### ISSUE THREAD

**Issue by yxr123321** [sbmlteam/libsbml#337]
How to use the configure options "--enable-fbc --enable-groups? double click the configure file? or change the configure file

**Comment by luciansmith** [comment]
Those are command-line options passed to cmake (or, potentially, options you select when you run 'cmake-guil').  

I assume you're trying to build libsbml?  What instructions are you looking at?

**Comment by yxr123321** [comment]
Yes, I am looking at this docs(https://github.com/cran/sybilSBML/blob/master/inst/INSTALL)

**Comment by luciansmith** [comment]
Got it!  OK, the libsbml installation instructions are at

https://synonym.caltech.edu/software/libsbml/5.18.0/docs/formatted/python-api/libsbml-installation.html

As you follow those instructions, just make sure that you turn on 'enable-fbc' and 'enable-groups' as you go.

**Comment by yxr123321** [comment]
OK. Thank you very much! I successfully installed the libSBML in R, because I can successfully library(libSBML). But currently my question is that I cannot install sybilSBML when using the command of R CMD INSTALL sybilSBML_3.1.3.tar.gz. Here is the error. Would you please help me again?
15 warnings and 2 errors generated.
make: *** [sybilSBML.o] Error 1
ERROR: compilation failed for package ‘sybilSBML’

**Comment by yxr123321** [comment]
This is the details.

/usr/local/include/sbml/packages/fbc/sbml/FluxObjective.h:1177:1: error: unknown type name 'FbcVariableType_t'
FbcVariableType_t
^
/usr/local/include/sbml/packages/fbc/sbml/FluxObjective.h:1401:31: error: unknown type name 'FbcVariableType_t'

**Comment by luciansmith** [comment]
It looks like you are not the only person having installation problems with sybilSBML:

https://cran.r-project.org/web/packages/sybilSBML/index.html

In fact, development of sybil itself seems to have stopped, to the point where it no longer works:

https://cran.r-project.org/web/packages/sybil/index.html

As such, it looks to me like you can either just use an older computer (or Docker image) with a working version of sybil and sybilSBML, or switch to just using libsbml directly, or find a different flux balance analysis package in R that works with SBML.  Sorry about that!  It's possible that @bgoli has a suggestion here?  I don't know what people who used to use sybil are switching to.

**Comment by yxr123321** [comment]
Sorry to disturb. I wonder know how to load the model data with SBML format? It seems like only TSV format is supported to load in SYBIL package

**Comment by skeating** [comment]
we are not the editors of the SYBIL package and can't really help with this any more than Lucian has already done
