### ISSUE TITLE
Typo in the tag name

### ISSUE THREAD

**Issue by SolunarNexus** [sbmlteam/libsbml#372]
I found a typo during *syntactic* testing in the file `syntactic_tests.v3.4.0/syntactic/21104/21104-fail-01-13-sev2-l3v1.xml` on line 33 where element name is `modiferSpeciesReference` (missing 'i', correct modif<ins>i</ins>erSpeciesReference).

**Comment by luciansmith** [comment]
The validation rule these models are supposed to be checking is if there are incorrect elements as children in the listOfReactants, so technically, both 'modifierSpeciesReference' objects and 'modiferSpeciesReference' objects are both illegal.  However, it's a stronger test to check correctly spelled things in the wrong place than incorrectly spelled things in the wrong place, so I've gone ahead and put in a pull request for the change.  Thank you for reporting the issue!
