### ISSUE TITLE
add tags to the repo

### ISSUE THREAD

**Issue by teto** [sbmlteam/libsbml#49]
Hi,

Would it be possible to tag the latest releases 5.18 / 5.17 please ? make it easier to navigate / goto releases in git.

I was first looking at https://github.com/opencor/libsbml but this repo looks like the original one ?

**Comment by fbergmann** [comment]
we have just moved the project to github from sf, where the previous releases are tagged. 

<https://sourceforge.net/projects/sbml/>

the next release will definitely be tagged right from here.

**Comment by teto** [comment]
seems like 2eb77ec005b0a26d2aa073cda69109a5a999293e was the latest release (5.18.1), I will try that one. thanks.
