### ISSUE TITLE
Potential Memory Leak in `getListOfAllElements`

### ISSUE THREAD

**Issue by FFroehlich** [sbmlteam/libsbml#57]
https://github.com/AMICI-dev/AMICI/pull/1310/checks?check_run_id=1284234058 suggests that calling `getListOfAllElements` is leaking memory. 

Can be reproduced with the following function: https://github.com/AMICI-dev/AMICI/blob/96df68d11e7fcb6db1bb717a2b5417070182a7d3/python/amici/sbml_import.py#L1830

**Comment by fbergmann** [comment]
hello fabian, this will be the same issue, as last time that we will have to mark it as %newobject for the swig bindings.

**Comment by fbergmann** [comment]
@FFroehlich i've committed a fix to the branch in the pull request, it would be good to know if this solves your issue.
